--- #YAML:1.0
name:                CPAN-Unwind
version:             0.05
abstract:            Recursively determines dependencies of CPAN modules
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Algorithm::Dependency::Ordered: 0
    Archive::Tar:                  0
    Cache::Cache:                  0
    Cache::FileCache:              0
    CPAN:                          0
    Data::Dumper:                  0
    File::Temp:                    0
    Log::Log4perl:                 0
    LWP::Simple:                   0
    Module::Depends::Intrusive:    0
    Pod::Usage:                    0
    Storable:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Mike Schilli <cpan@perlmeister.com>
